/**
 * Build-time Tailwind config.
 *
 * Replaces the former `cdn.tailwindcss.com` script + inline `tailwind.config`
 * in index.html. The CDN build compiled styles in the browser at runtime, which
 * left the packaged mobile apps unstyled without a network connection.
 *
 * Every colour resolves to a CSS custom property so the `.dark` class on <html>
 * re-themes the app without touching component markup. Token values live in
 * styles/theme.css (generated by scripts/generate-theme-css.mjs).
 */

const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

const NEUTRALS = ['slate', 'gray', 'zinc', 'neutral', 'stone'];
const ACCENTS = [
  'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal',
  'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
];

/**
 * Colours carry two variables, not one.
 *
 * A ramp step means opposite things in its two roles, and they move in opposite
 * directions when the theme flips: `text-gray-800` is dark body copy that has to
 * become light, while `bg-gray-800` is a dark slab that has to stay dark (or the
 * `text-white` sitting on it disappears). `--ct-*` backs the text scales and
 * `--cb-*` backs surfaces, borders, rings and gradients. In the light theme both
 * hold the same value, so light mode is unchanged.
 *
 * `rgb(var(--x) / <alpha-value>)` keeps Tailwind's `/50` opacity modifiers working.
 */
const text = (token) => `rgb(var(--ct-${token}) / <alpha-value>)`;
const surface = (token) => `rgb(var(--cb-${token}) / <alpha-value>)`;

/** Expands one family into a themed 50–950 ramp using the given role. */
const ramp = (family, role) =>
  Object.fromEntries(STEPS.map((step) => [step, role(`${family}-${step}`)]));

const rampsFor = (role) =>
  Object.fromEntries(
    [...NEUTRALS, ...ACCENTS].map((family) => [family, ramp(family, role)]),
  );

const surfaceRamps = rampsFor(surface);
const textRamps = rampsFor(text);

/** Brand colours, expanded for one role. */
const brand = (v) => ({
  primary: { DEFAULT: v('primary'), light: v('primary-light'), dark: v('primary-dark') },
  secondary: {
    DEFAULT: v('secondary'),
    light: v('secondary-light'),
    dark: v('secondary-dark'),
  },
  success: v('success'),
  warning: v('warning'),
  danger: v('danger'),
  // `dark` is a text colour and `light` a surface colour in this design system.
  dark: v('ui-dark'),
  light: v('ui-light'),
  // `border-border` keeps its hairline; `default`/`strong` are the semantic roles.
  border: { DEFAULT: v('ui-border'), default: v('sem-border-default'), strong: v('sem-border-strong') },
  // Editorial landing palette — ink on paper with one vermilion accent.
  paper: { DEFAULT: v('paper'), deep: v('paper-deep'), bright: v('paper-bright') },
  ink: { DEFAULT: v('ink'), soft: v('ink-soft'), faint: v('ink-faint') },
  ember: { DEFAULT: v('ember'), deep: v('ember-deep'), tint: v('ember-tint') },
  surface: {
    DEFAULT: v('surface'),
    raised: v('surface-raised'),
    // Semantic surfaces: the page, a card on it, a sheet or popover above that.
    canvas: v('sem-surface-canvas'),
    panel: v('sem-surface-panel'),
    elevated: v('sem-surface-elevated'),
  },
});

/**
 * Semantic roles (docs/career-os/DESIGN_SYSTEM.md), generated as `--ct-sem-*`
 * / `--cb-sem-*` aliases of existing values. The text roles are named
 * `content` rather than `text` so the utilities read as `text-content-secondary`
 * instead of colliding with Tailwind's own `text-*` prefix. `surface.*` and
 * `border.*` live in `brand()` above so they merge with the existing keys.
 *
 *   text-content-primary   bg-surface-panel      border-border-strong
 *   text-evidence-inferred bg-status-warning/10  ring-focus-ring
 */
const semantic = (v) => ({
  content: {
    primary: v('sem-text-primary'),
    secondary: v('sem-text-secondary'),
    muted: v('sem-text-muted'),
  },
  action: { primary: v('sem-action-primary'), secondary: v('sem-action-secondary') },
  status: {
    success: v('sem-status-success'),
    warning: v('sem-status-warning'),
    danger: v('sem-status-danger'),
    info: v('sem-status-info'),
  },
  focus: { ring: v('sem-focus-ring') },
  evidence: {
    verified: v('sem-evidence-verified'),
    confirmed: v('sem-evidence-confirmed'),
    inferred: v('sem-evidence-inferred'),
    incomplete: v('sem-evidence-incomplete'),
  },
});

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './index.tsx',
    './App.tsx',
    './constants.ts',
    './exampleData.ts',
    './types.ts',
    './components/**/*.{ts,tsx}',
    './services/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './config/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      /**
       * The default scale. Everything that is not text — backgrounds, borders,
       * rings, divides and gradient stops — inherits from here, so it uses the
       * surface role.
       */
      colors: {
        ...surfaceRamps,
        ...brand(surface),
        ...semantic(surface),
        /**
         * Gradient stops, rings and divides all read from this scale, so `white`
         * has to be the themed surface here — `to-white/90` on a card must not
         * stay literally white in dark mode. `text-white` is pinned back to real
         * white in the `textColor` block below.
         */
        white: surface('surface'),
        glass: {
          border: 'rgba(var(--cb-glass-border))',
          surface: 'rgba(var(--cb-glass-surface))',
          highlight: 'rgba(var(--cb-glass-highlight))',
        },
      },
      /** Text overrides the default scale to use the text role. */
      textColor: {
        ...textRamps,
        ...brand(text),
        ...semantic(text),
        // Labels on solid accent buttons stay white in both themes.
        white: '#ffffff',
      },
      placeholderColor: {
        ...textRamps,
        ...brand(text),
        ...semantic(text),
        white: '#ffffff',
      },
      textDecorationColor: {
        ...textRamps,
        ...brand(text),
        ...semantic(text),
        white: '#ffffff',
      },
      /**
       * `bg-white` (365 uses) means "the page surface" and must darken, while
       * `text-white` (168 uses) labels brand-coloured buttons and must stay
       * white. Tailwind keys these scales separately, so the split lives here.
       */
      backgroundColor: {
        white: surface('surface'),
        'true-white': '#ffffff',
        /**
         * For marks drawn as elements rather than glyphs — icon bars, rules,
         * progress ticks. They are foreground, so they take the *text* role and
         * invert along with the copy. Using `bg-ink` for these would leave a
         * dark mark on a dark surface, because `bg-ink` correctly stays dark as
         * a slab colour.
         */
        mark: text('ink'),
        'mark-soft': text('ink-soft'),
      },
      borderColor: {
        white: surface('surface'),
        'true-white': '#ffffff',
      },
      divideColor: {
        white: surface('surface'),
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Fraunces', 'Georgia', 'serif'],
        body: ['"Instrument Sans"', 'system-ui', 'sans-serif'],
        label: ['"Spline Sans Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(0, 0, 0, 0.05)',
        'glass-hover': '0 12px 40px 0 rgba(0, 0, 0, 0.10)',
        glow: '0 0 20px rgba(117, 130, 252, 0.3)',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
    },
  },
  plugins: [],
};
