#!/usr/bin/env node
/**
 * Career OS translation helper.
 *
 *   node scripts/career-os-i18n.mjs --missing            # print keys used in code but absent from the English catalogue (JSON)
 *   node scripts/career-os-i18n.mjs --apply <file.json>  # insert {key: {en, es, fr, de}} entries into every locale block
 *
 * Keys are collected from t('key', 'default') calls (single or multi-line) under
 * the Career OS surfaces. English defaults come from the code; the other three
 * locales must be supplied in the JSON handed to --apply, so no locale ever
 * receives an untranslated English string silently (translationCoverage.test.ts
 * enforces parity).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CATALOG = path.join(ROOT, 'services/translationService.tsx');
const SCAN_DIRS = ['components/careeros', 'components/prism', 'components/ResumeBuilder.tsx', 'components/SmartStudio.tsx', 'lib/builder', 'App.tsx'];
const LOCALES = ['en', 'es', 'fr', 'de'];

function* walk(p) {
  const full = path.join(ROOT, p);
  const stat = fs.statSync(full);
  if (stat.isFile()) { if (/\.(tsx?|mjs)$/.test(full) && !/__tests__/.test(full)) yield full; return; }
  for (const entry of fs.readdirSync(full)) {
    if (entry === 'node_modules' || entry === '__tests__') continue;
    yield* walk(path.join(p, entry));
  }
}

const CALL_RE = /\bt\(\s*'((?:[^'\\]|\\.)*)'\s*,\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|`((?:[^`\\]|\\.)*)`)/g;

function usedKeys() {
  const out = new Map();
  for (const dir of SCAN_DIRS) {
    if (!fs.existsSync(path.join(ROOT, dir))) continue;
    for (const file of walk(dir)) {
      const src = fs.readFileSync(file, 'utf8');
      for (const m of src.matchAll(CALL_RE)) {
        const key = m[1];
        const def = (m[2] ?? m[3] ?? m[4] ?? '').replace(/\\'/g, "'");
        if (!out.has(key)) out.set(key, def);
      }
    }
  }
  return out;
}

function catalogKeys(locale) {
  const src = fs.readFileSync(CATALOG, 'utf8');
  const block = src.match(new RegExp(`^    ${locale}: \\{([\\s\\S]*?)^    \\},?$`, 'm'));
  if (!block) throw new Error(`locale block ${locale} not found`);
  return new Set([...block[1].matchAll(/^\s+'([^']+)':/gm)].map((m) => m[1]));
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

function apply(entries) {
  let src = fs.readFileSync(CATALOG, 'utf8');
  for (const locale of LOCALES) {
    const existing = catalogKeys(locale);
    const lines = Object.entries(entries)
      .filter(([key]) => !existing.has(key))
      .map(([key, values]) => {
        const value = values[locale];
        if (typeof value !== 'string' || !value.trim()) throw new Error(`missing ${locale} for ${key}`);
        return `        '${esc(key)}': '${esc(value)}',`;
      });
    if (lines.length === 0) continue;
    const marker = new RegExp(`(^    ${locale}: \\{\\n)`, 'm');
    if (!marker.test(src)) throw new Error(`locale block ${locale} not found`);
    src = src.replace(marker, `$1        // Career OS (generated by scripts/career-os-i18n.mjs)\n${lines.join('\n')}\n`);
  }
  fs.writeFileSync(CATALOG, src);
}

const [, , mode, file] = process.argv;
if (mode === '--missing') {
  const en = catalogKeys('en');
  const used = usedKeys();
  const missing = {};
  for (const [key, def] of used) if (!en.has(key)) missing[key] = def;
  process.stdout.write(JSON.stringify(missing, null, 2) + '\n');
  console.error(`${Object.keys(missing).length} keys missing from the English catalogue (of ${used.size} used).`);
} else if (mode === '--apply' && file) {
  const entries = JSON.parse(fs.readFileSync(file, 'utf8'));
  apply(entries);
  console.log(`applied ${Object.keys(entries).length} keys to ${LOCALES.join('/')}`);
} else {
  console.error('usage: --missing | --apply <file.json>');
  process.exit(1);
}
